# Fraud Detection Dataset : Kaggle 
https://www.kaggle.com/volodymyrgavrysh/fraud-detection-bank-dataset-20k-records-binary

In [75]:
import pandas as pd
import numpy as np
import matplotlib
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import confusion_matrix, classification_report

In [5]:
pd.set_option("display.max_rows", None, "display.max_columns", None)

In [3]:
fraud_data = pd.read_csv("fraud_detection_bank_dataset.csv")
fraud_data.head()

Unnamed: 0  col_0  col_1  col_2  col_3  col_4  col_5  col_6  col_7  col_8  \
0           0      9   1354      0     18      0      1      7      9      0   
1           1      0    239      0      1      0      1      0      0      0   
2           2      0    260      0      4      0      3      6      0      0   
3           3     17    682      0      1      0      0      8     17      0   
4           4      1    540      0      2      0      1      7      1      0   

   ...  col_103  col_104  col_105  col_106  col_107  col_108  col_109  \
0  ...        0        0        0        1        1        0        0   
1  ...        0        1        0        0        0        0        0   
2  ...        0        0        0        1        1        0        0   
3  ...        0        1        0        1        1        0        0   
4  ...        0        0        0        1        1        0        0   

   col_110  col_111  targets  
0        0       49        1  
1        0       55        1  
2        0       56        1  
3        0       65        1  
4        0      175        1  

[5 rows x 114 columns]

In [6]:
fraud_data.describe()

Unnamed: 0         col_0         col_1         col_2         col_3  \
count  20468.000000  20468.000000  20468.000000  20468.000000  20468.000000   
mean   10233.500000      3.226256    294.793043      0.420021      2.329343   
std     5908.746991     20.564308    717.541984      7.367275     10.068512   
min        0.000000      0.000000      0.000000      0.000000      0.000000   
25%     5116.750000      0.000000     38.000000      0.000000      0.000000   
50%    10233.500000      0.000000     97.000000      0.000000      1.000000   
75%    15350.250000      2.000000    283.000000      0.000000      2.000000   
max    20467.000000   2301.000000  37808.000000    904.000000    772.000000   

              col_4         col_5         col_6         col_7    col_8  \
count  20468.000000  20468.000000  20468.000000  20468.000000  20468.0   
mean       0.083594      0.939857      2.386066      3.226256      0.0   
std        0.840537      4.222896      3.018140     20.564308      0.0   
min        0.000000      0.000000     -1.000000      0.000000      0.0   
25%        0.000000      0.000000      0.000000      0.000000      0.0   
50%        0.000000      0.000000      2.000000      0.000000      0.0   
75%        0.000000      1.000000      6.000000      2.000000      0.0   
max       54.000000    230.000000     11.000000   2301.000000      0.0   

         col_9   col_10   col_11   col_12        col_13        col_14  \
count  20468.0  20468.0  20468.0  20468.0  20468.000000  20468.000000   
mean       0.0      0.0      0.0      0.0      0.038646      0.363152   
std        0.0      0.0      0.0      0.0      0.192754      0.480920   
min        0.0      0.0      0.0      0.0      0.000000      0.000000   
25%        0.0      0.0      0.0      0.0      0.000000      0.000000   
50%        0.0      0.0      0.0      0.0      0.000000      0.000000   
75%        0.0      0.0      0.0      0.0      0.000000      1.000000   
max        0.0      0.0      0.0      0.0      1.000000      1.000000   

             col_15        col_16         col_17   col_18   col_19   col_20  \
count  20468.000000  20468.000000   20468.000000  20468.0  20468.0  20468.0   
mean       0.330760      0.412644     196.679500      0.0      0.0      0.0   
std        0.470498      0.492322    6700.095223      0.0      0.0      0.0   
min        0.000000      0.000000       0.000000      0.0      0.0      0.0   
25%        0.000000      0.000000       0.000000      0.0      0.0      0.0   
50%        0.000000      0.000000       0.000000      0.0      0.0      0.0   
75%        1.000000      1.000000       0.000000      0.0      0.0      0.0   
max        1.000000      1.000000  646622.000000      0.0      0.0      0.0   

        col_21        col_22        col_23        col_24        col_25  \
count  20468.0  20468.000000  20468.000000  20468.000000  20468.000000   
mean       0.0      4.220344     34.201290      3.068790      2.701925   
std        0.0     29.063427    126.109375     12.768477     14.340519   
min        0.0      0.000000      0.000000      0.000000      0.000000   
25%        0.0      0.000000      2.000000      1.000000      0.000000   
50%        0.0      0.000000      7.000000      1.000000      0.000000   
75%        0.0      2.000000     25.000000      2.000000      1.000000   
max        0.0   3349.000000  11480.000000    909.000000    693.000000   

             col_26        col_27        col_28        col_29        col_30  \
count  20468.000000  20468.000000  20468.000000  20468.000000  20468.000000   
mean       0.875562      0.038597      0.999951      1.409078      6.184043   
std        4.880614      0.315826      0.006990      2.959671     22.127733   
min        0.000000      0.000000      0.000000      0.000000      0.000000   
25%        0.000000      0.000000      1.000000      0.000000      0.000000   
50%        0.000000      0.000000      1.000000      1.000000      0.000000   
75%        0.000000      0.000000      1

Checking if any of the columns contain any missing values

In [7]:
fraud_data.isnull().sum()

Unnamed: 0    0
col_0         0
col_1         0
col_2         0
col_3         0
col_4         0
col_5         0
col_6         0
col_7         0
col_8         0
col_9         0
col_10        0
col_11        0
col_12        0
col_13        0
col_14        0
col_15        0
col_16        0
col_17        0
col_18        0
col_19        0
col_20        0
col_21        0
col_22        0
col_23        0
col_24        0
col_25        0
col_26        0
col_27        0
col_28        0
col_29        0
col_30        0
col_31        0
col_32        0
col_33        0
col_34        0
col_35        0
col_36        0
col_37        0
col_38        0
col_39        0
col_40        0
col_41        0
col_42        0
col_43        0
col_44        0
col_45        0
col_46        0
col_47        0
col_48        0
col_49        0
col_50        0
col_51        0
col_52        0
col_53        0
col_54        0
col_55        0
col_56        0
col_57        0
col_58        0
col_59        0
col_60        0
col_61  

There are no missing values. So we need not handle them. We now proceed to check if there are any duplicates.

In [36]:
fraud_data.duplicated().sum()

0

There are no duplicates as well so we can now proceed any remove any unwanted columns.
The first column is Index value and it is not of any use for our analysis and hence it can be removed.

In [108]:
X = fraud_data.drop(["Unnamed: 0"], axis=1)


We now check if any of the columns are correlated and delete columns that are highly correlated. 

In [109]:
corr_df = X.corr()
for i in range(len(corr_df.columns)):
    correlated = [corr_df.iloc[:,i]>=0.9]
    if len(np.nonzero(correlated)[1])>1:
        print(np.nonzero(correlated)[1])
   

[ 0  7 22]
[ 0  7 22]
[ 0  7 22]
[36 40 47 49 50 55 57 63 64 65 66]
[37 56]
[38 54]
[36 40 47 50 55 57 63 66]
[42 60 64]
[44 62]
[36 40 47 50 55 57 63 64 66]
[36 49 55 60 65]
[36 40 47 50 55 57 63 66]
[38 54]
[36 40 47 49 50 55 57 63 64 65 66]
[37 56]
[36 40 47 50 55 57 63 66]
[42 49 60 64 65]
[44 62]
[36 40 47 50 55 57 63 66]
[36 42 47 55 60 64]
[36 49 55 60 65]
[36 40 47 50 55 57 63 66]


In [110]:
X = X.drop(["col_7",'col_22',"col_40","col_47","col_49","col_50","col_55","col_57","col_63","col_64","col_65","col_66","col_56","col_54","col_60","col_64","col_62","col_50"], axis=1)

After removing the unnecessary columns, we now proceed to check if the dataset is balanced or imbalanced.

In [111]:
X['targets'].value_counts()

0    15030
1     5438
Name: targets, dtype: int64

As expected, the dataset is imbalanced and hence we balance the dataset by removing target-0 records.

In [112]:
X_0 =X[X['targets']==0][:8500]
X_1 =X[X['targets']==1]
df = pd.concat([X_0,X_1],axis=0)
X = df.drop('targets',axis=1)

In [113]:
target = df['targets']
target.value_counts()

0    8500
1    5438
Name: targets, dtype: int64

Next we split the dataset into training and test set.
We further normalize the dataset.

In [114]:
X_train, X_test, y_train, y_test = train_test_split(X, target, random_state = 0, test_size = 0.3)

scaler = StandardScaler()
scaler.fit(X_train)
X_train = scaler.transform(X_train)
X_test = scaler.transform(X_test)

We first try the logistic regression model

In [115]:
model = LogisticRegression()
model.fit(X_train, y_train)

print(model.score(X_test, y_test))

0.8582018173122907


C:\Users\Ramu Endluri\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\sklearn\linear_model\_logistic.py:814: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


We then check the decision tree performance with our data

In [116]:
dt = DecisionTreeClassifier()
dt.fit(X_train, y_train)
y_pred = dt.predict(X_test)
dt.score(X_test, y_test)

0.8837876614060258

In [117]:
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.91      0.90      0.90      2521
           1       0.85      0.86      0.85      1661

    accuracy                           0.88      4182
   macro avg       0.88      0.88      0.88      4182
weighted avg       0.88      0.88      0.88      4182



In [118]:
confusion_matrix(y_test, y_pred)

array([[2271,  250],
       [ 236, 1425]], dtype=int64)

Finally, we check with random forests

In [148]:
rf = RandomForestClassifier(max_features=10, min_samples_split=5, min_samples_leaf=5,n_estimators= 100, criterion='gini')
#rf = RandomForestClassifier(max_features=5, min_samples_split=5, min_samples_leaf=5, oob_score=True,n_estimators= 300, criterion='entropy')

In [149]:
rf.fit(X_train, y_train)
y_pred = rf.predict(X_test)
print(rf.score(X_test, y_test))
print(classification_report(y_test, y_pred))
print(confusion_matrix(y_test, y_pred))

0.9103299856527977
              precision    recall  f1-score   support

           0       0.91      0.94      0.93      2521
           1       0.91      0.86      0.88      1661

    accuracy                           0.91      4182
   macro avg       0.91      0.90      0.91      4182
weighted avg       0.91      0.91      0.91      4182

[[2382  139]
 [ 236 1425]]


The random forest classifier worked best among all these models.